export enum GoodPoint {
  FAV = '취향 저격',
  FAST = '빨리 읽혀요',
  IMMERSIVE = '몰입감이 좋아요',
  LINGERING = '여운이 남아요',
  ELOQUENT = '표현이 수려해요',
  PRACTICAL = '실용적이에요',
  TRENDY = '트렌디해요',
  COMFORTING = '위로를 받아요',
  GROWTH = '성장을 자극받아요',
  INSIGHT = '인사이트 있어요',
  PROFESSIONAL = '전문적이에요',
  WORK_READY = '실무에 적합해요',
  EASY = '쉽게 이해돼요',
  THOUGHT_PROVOKING = '생각할 거리가 많아요',
  TIMELESS = '시대를 초월한 가치',
  PERCEPTIVE = '통찰력이 뛰어나요',
  BALANCED = '균형 잡힌 시각이에요',
  INFORMATIVE = '유익해요',
  DETAILED = '설명이 구체적이에요',
  CULTURAL = '교양 쌓기에 좋아요',
}
